apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyrator
  namespace: default
spec:
  selector:
    matchLabels:
      name: copyrator
  template:
    metadata:
      labels:
        name: copyrator
    spec:
      serviceAccountName: copyrator-acc
      containers:
      - name: copyrator
        image: ramezbenaribia/datapomm:latest
        # imagePullPolicy: Always
        # args: ["--rule-name", "odoo-instances-1"]
        ports:
        - containerPort: 8000
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1 
kind: Service
metadata: 
  name: copyrator-service
spec: 
  selector: 
    app: copyrator
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000 
