---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: copyrator-acc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: copyrator-rc
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["operators.datapm.pomm"]
    resources: ["copyrators"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: copyrator-crb
subjects:
- kind: ServiceAccount
  name: copyrator-acc
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: copyrator-rc
